cc = clang-format
CFLAGS = -Wall -Wextra -Werror -Wpedantic -g
LFLAGS = $(shell pkg-config --libs gmp)

.PHONY: all clean

all: encrypt keygen decrypt

encrypt: encrypt.o
	$(CC) numtheory.o randstate.o rsa.o -o encrypt encrypt.o $(LFLAGS)

keygen: keygen.o
	$(CC) numtheory.o randstate.o rsa.o -o keygen keygen.o $(LFLAGS)

decrypt: decrpyt.o
	$(CC) numtheory.o randstate.o rsa.o -o decrypt decrypt.o $(LFLAGS)

format:
	clang-format -i -style=file *[c,h]

clean:
	rm -f decrypt decrypt.o
	rm -f encrypt encrypt.o
	rm -f keygen keygen.o 
